var express = require('express');
var app = express();
var mustacheExpress = require('mustache-express');
var bodyParser = require('body-parser');

var anyDB = require('any-db');
var conn = anyDB.createConnection('sqlite3://seniorLeaves.db.sqlite3');
conn.query("DROP TABLE seniorLeaves")
conn.query("CREATE TABLE IF NOT EXISTS seniorLeaves (username TEXT, name TEXT, email TEXT, password TEXT, remaingleaves INTEGER, starttime TIMESTAMP, endtime TIMESTAMP, onleave INTEGER)");

conn.query("INSERT INTO seniorLeaves (username, name, email, password) VALUES (?, ?, ?, ?)", ['rbeisswanger', 'Russel Beisswanger', 'rbeisswanger@students.stab.org', 'betterRedThanExpert'])
conn.query("INSERT INTO seniorLeaves (username, name, email, password) VALUES (?, ?, ?, ?)", ['ablanton', 'Adele Blanton', 'ablanton@students.stab.org', 'betterRedThanExpert'])
conn.query("INSERT INTO seniorLeaves (username, name, email, password) VALUES (?, ?, ?, ?)", ['kbooth', 'Kellie Booth','kbooth@students.stab.org', 'betterRedThanExpert'])
conn.query("INSERT INTO seniorLeaves (username, name, email, password) VALUES (?, ?, ?, ?)", ['gborton', 'Gillian Borton', 'gborton@students.stab.org', 'betterRedThanExpert'])
conn.query("INSERT INTO seniorLeaves (username, name, email, password) VALUES (?, ?, ?, ?)", ['jconrades', 'Jenna Conrades', 'jconrades@students.stab.org', 'betterRedThanExpert'])
conn.query("INSERT INTO seniorLeaves (username, name, email, password) VALUES (?, ?, ?, ?)", ['hdeal', 'Henry Deal', 'hdeal@students.stab.org', 'betterRedThanExpert'])
conn.query("INSERT INTO seniorLeaves (username, name, email, password) VALUES (?, ?, ?, ?)", ['pdevillier', 'Parker DeVillier', 'pdevillier@students.stab.org', 'betterRedThanExpert'])
conn.query("INSERT INTO seniorLeaves (username, name, email, password) VALUES (?, ?, ?, ?)", ['cgregg', 'Carter Gregg', 'cgregg@students.stab.org', 'betterRedThanExpert'])
conn.query("INSERT INTO seniorLeaves (username, name, email, password) VALUES (?, ?, ?, ?)", ['sdulaney', 'Sarah Dulaney', 'sdulaney@students.stab.org', 'betterRedThanExpert'])
conn.query("INSERT INTO seniorLeaves (username, name, email, password) VALUES (?, ?, ?, ?)", ['afarrell', 'Anna Farrell', 'afarrell@students.stab.org', 'betterRedThanExpert'])
conn.query("INSERT INTO seniorLeaves (username, name, email, password) VALUES (?, ?, ?, ?)", ['jfrazier', 'Jayne Frazier', 'jfrazier@students.stab.org', 'betterRedThanExpert'])
conn.query("INSERT INTO seniorLeaves (username, name, email, password) VALUES (?, ?, ?, ?)", ['kgoldstein', 'Katie Goldstein', 'kgoldstein@students.stab.org', 'betterRedThanExpert'])
conn.query("INSERT INTO seniorLeaves (username, name, email, password) VALUES (?, ?, ?, ?)", ['ngoodkin', 'Nina Goodkin', 'ngoodkin@students.stab.org', 'betterRedThanExpert'])
conn.query("INSERT INTO seniorLeaves (username, name, email, password) VALUES (?, ?, ?, ?)", ['jhartwig', 'Jacqueline Hartwig', 'jhartwig@students.stab.org', 'betterRedThanExpert'])
conn.query("INSERT INTO seniorLeaves (username, name, email, password) VALUES (?, ?, ?, ?)", ['mhenderson', 'Martha Henderson', 'mhenderson@students.stab.org', 'betterRedThanExpert'])
conn.query("INSERT INTO seniorLeaves (username, name, email, password) VALUES (?, ?, ?, ?)", ['lhoerr', 'Lucia Hoerr', 'lhoerr@students.stab.org', 'betterRedThanExpert'])
conn.query("INSERT INTO seniorLeaves (username, name, email, password) VALUES (?, ?, ?, ?)", ['nkent', 'Nic Kent', 'nkent@students.stab.org', 'betterRedThanExpert'])
conn.query("INSERT INTO seniorLeaves (username, name, email, password) VALUES (?, ?, ?, ?)", ['alacour', 'Alexandra LaCour', 'alacour@students.stab.org', 'betterRedThanExpert'])
conn.query("INSERT INTO seniorLeaves (username, name, email, password) VALUES (?, ?, ?, ?)", ['slandes', 'Syd Landes', 'slandes@students.stab.org', 'betterRedThanExpert'])
conn.query("INSERT INTO seniorLeaves (username, name, email, password) VALUES (?, ?, ?, ?)", ['hlewis', 'Harrison Lewis', 'hlewis@students.stab.org', 'betterRedThanExpert'])
conn.query("INSERT INTO seniorLeaves (username, name, email, password) VALUES (?, ?, ?, ?)", ['jlindbergh', 'Johnny Lindbergh', 'jlindbergh@students.stab.org', 'betterRedThanExpert'])
conn.query("INSERT INTO seniorLeaves (username, name, email, password) VALUES (?, ?, ?, ?)", ['jlourie', 'Jacob Lourie', 'jlourie@students.stab.org', 'betterRedThanExpert'])
conn.query("INSERT INTO seniorLeaves (username, name, email, password) VALUES (?, ?, ?, ?)", ['jmilligan', 'Jack Milligan', 'jmilligan@students.stab.org', 'betterRedThanExpert'])
conn.query("INSERT INTO seniorLeaves (username, name, email, password) VALUES (?, ?, ?, ?)", ['momorris', 'Molly Morris', 'momorris@students.stab.org', 'betterRedThanExpert'])
conn.query("INSERT INTO seniorLeaves (username, name, email, password) VALUES (?, ?, ?, ?)", ['gtennery', 'Gabrielle Tennery', 'gtennery@students.stab.org', 'betterRedThanExpert'])
conn.query("INSERT INTO seniorLeaves (username, name, email, password) VALUES (?, ?, ?, ?)", ['jpausic', 'Jack Pausic', 'jpausic@students.stab.org', 'betterRedThanExpert'])
conn.query("INSERT INTO seniorLeaves (username, name, email, password) VALUES (?, ?, ?, ?)", ['gsanok', 'Gabe Sanok', 'gsanok@students.stab.org', 'betterRedThanExpert'])
conn.query("INSERT INTO seniorLeaves (username, name, email, password) VALUES (?, ?, ?, ?)", ['sshah', 'Simran Shah', 'sshah@students.stab.org', 'betterRedThanExpert'])
conn.query("INSERT INTO seniorLeaves (username, name, email, password) VALUES (?, ?, ?, ?)", ['mtripathi', 'Mansi Tripathi', 'mtripathi@students.stab.org', 'betterRedThanExpert'])
conn.query("INSERT INTO seniorLeaves (username, name, email, password) VALUES (?, ?, ?, ?)", ['svanwincoop', 'Sophia Van Wincoop', 'svanwincoop@students.stab.org', 'betterRedThanExpert'])
conn.query("INSERT INTO seniorLeaves (username, name, email, password) VALUES (?, ?, ?, ?)", ['cweis', 'Caleigh Weis', 'cweis@students.stab.org', 'betterRedThanExpert'])
conn.query("INSERT INTO seniorLeaves (username, name, email, password) VALUES (?, ?, ?, ?)", ['awood', 'Andy Wood', 'awood@students.stab.org', 'betterRedThanExpert'])
conn.query("INSERT INTO seniorLeaves (username, name, email, password) VALUES (?, ?, ?, ?)", ['sakhaterzai', 'Sais Khaterzai','sakhaterzai@students.stab.org', 'betterRedThanExpert'])
conn.query("INSERT INTO seniorLeaves (username, name, email, password) VALUES (?, ?, ?, ?)", ['jlondon', 'Jaicyn London', 'jlondon@students.stab.org', 'betterRedThanExpert'])
conn.query("INSERT INTO seniorLeaves (username, name, email, password) VALUES (?, ?, ?, ?)", ['aculver', 'Andrew Culver', 'aculver@students.stab.org', 'betterRedThanExpert'])
conn.query("INSERT INTO seniorLeaves (username, name, email, password) VALUES (?, ?, ?, ?)", ['emtrebour', 'Emily Trebour', 'emtrebour@students.stab.org', 'betterRedThanExpert'])
conn.query("INSERT INTO seniorLeaves (username, name, email, password) VALUES (?, ?, ?, ?)", ['sanderson', 'Samantha Anderson', 'sanderson@students.stab.org', 'betterRedThanExpert'])
conn.query("INSERT INTO seniorLeaves (username, name, email, password) VALUES (?, ?, ?, ?)", ['mdigiacomo', 'Michael DiGiacomo', 'mdigiacomo@students.stab.org', 'betterRedThanExpert'])
conn.query("INSERT INTO seniorLeaves (username, name, email, password) VALUES (?, ?, ?, ?)", ['cmurphy', 'Chris Murphy', 'cmurphy@students.stab.org', 'betterRedThanExpert'])
conn.query("INSERT INTO seniorLeaves (username, name, email, password) VALUES (?, ?, ?, ?)", ['jakeville', 'Jack Keville', 'jkeville@students.stab.org', 'betterRedThanExpert'])
conn.query("INSERT INTO seniorLeaves (username, name, email, password) VALUES (?, ?, ?, ?)", ['latherton', 'Luke Atherton', 'latherton@students.stab.org', 'betterRedThanExpert'])
conn.query("INSERT INTO seniorLeaves (username, name, email, password) VALUES (?, ?, ?, ?)", ['jbrown', 'Javaneh Brown', 'jabrown@students.stab.org', 'betterRedThanExpert'])
conn.query("INSERT INTO seniorLeaves (username, name, email, password) VALUES (?, ?, ?, ?)", ['edameron', 'Eliza Dameron', 'edameron@students.stab.org', 'betterRedThanExpert'])
conn.query("INSERT INTO seniorLeaves (username, name, email, password) VALUES (?, ?, ?, ?)", ['makosefeski', 'Matt Kosefeski', 'makosefeski@students.stab.org', 'betterRedThanExpert'])
conn.query("INSERT INTO seniorLeaves (username, name, email, password) VALUES (?, ?, ?, ?)", ['smcnamara', 'Sam McNamara', 'smcnamara@students.stab.org', 'betterRedThanExpert'])
conn.query("INSERT INTO seniorLeaves (username, name, email, password) VALUES (?, ?, ?, ?)", ['whass', 'William Hass', 'whass@students.stab.org', 'betterRedThanExpert'])
conn.query("INSERT INTO seniorLeaves (username, name, email, password) VALUES (?, ?, ?, ?)", ['sismith', 'Sierra Smith','ssmith@students.stab.org', 'betterRedThanExpert'])
conn.query("INSERT INTO seniorLeaves (username, name, email, password) VALUES (?, ?, ?, ?)", ['camorris', 'Carter Morris', 'camorris@students.stab.org', 'betterRedThanExpert'])
conn.query("INSERT INTO seniorLeaves (username, name, email, password) VALUES (?, ?, ?, ?)", ['eswett', 'Evan Swett', 'eswett@students.stab.org', 'betterRedThanExpert'])
conn.query("INSERT INTO seniorLeaves (username, name, email, password) VALUES (?, ?, ?, ?)", ['lawaters', 'Lauren Waters', 'lwaters@students.stab.org', 'betterRedThanExpert'])
conn.query("INSERT INTO seniorLeaves (username, name, email, password) VALUES (?, ?, ?, ?)", ['kwaters', 'Katie Waters', 'kwaters@students.stab.org', 'betterRedThanExpert'])
conn.query("INSERT INTO seniorLeaves (username, name, email, password) VALUES (?, ?, ?, ?)", ['eoconnor', 'Ellie OConner', 'eoconnor@students.stab.org', 'betterRedThanExpert'])
conn.query("INSERT INTO seniorLeaves (username, name, email, password) VALUES (?, ?, ?, ?)", ['miliu', 'Michelle Liu', 'mliu@students.stab.org', 'betterRedThanExpert'])
conn.query("INSERT INTO seniorLeaves (username, name, email, password) VALUES (?, ?, ?, ?)", ['msha', 'Ruoming Sha', 'rsha@students.stab.org', 'betterRedThanExpert'])
conn.query("INSERT INTO seniorLeaves (username, name, email, password) VALUES (?, ?, ?, ?)", ['cowu', 'Coco Wu', 'cowu@students.stab.org', 'betterRedThanExpert'])
conn.query("INSERT INTO seniorLeaves (username, name, email, password) VALUES (?, ?, ?, ?)", ['jafurin', 'Jasmine Furin', 'jfurin@students.stab.org', 'betterRedThanExpert'])
conn.query("INSERT INTO seniorLeaves (username, name, email, password) VALUES (?, ?, ?, ?)", ['sqi', 'Sara Qi', 'sqi@students.stab.org', 'betterRedThanExpert'])
conn.query("INSERT INTO seniorLeaves (username, name, email, password) VALUES (?, ?, ?, ?)", ['yiyao', 'Jerry Yao', 'yyao@students.stab.org', 'betterRedThanExpert'])
conn.query("INSERT INTO seniorLeaves (username, name, email, password) VALUES (?, ?, ?, ?)", ['kewang', 'Kevin Wang', 'kewang@students.stab.org', 'betterRedThanExpert'])
conn.query("INSERT INTO seniorLeaves (username, name, email, password) VALUES (?, ?, ?, ?)", ['lbrady', 'Logan Brady', 'lbrady@students.stab.org', 'betterRedThanExpert'])
conn.query("INSERT INTO seniorLeaves (username, name, email, password) VALUES (?, ?, ?, ?)", ['lzhang', 'Linsey Zhang','lzhang@students.stab.org', 'betterRedThanExpert'])
conn.query("INSERT INTO seniorLeaves (username, name, email, password) VALUES (?, ?, ?, ?)", ['dlovett', 'David Lovett', 'dlovett@students.stab.org', 'betterRedThanExpert'])
conn.query("INSERT INTO seniorLeaves (username, name, email, password) VALUES (?, ?, ?, ?)", ['ezhao', 'Emily Zhao', 'ezhao@students.stab.org', 'betterRedThanExpert'])
conn.query("INSERT INTO seniorLeaves (username, name, email, password) VALUES (?, ?, ?, ?)", ['ydang', 'Yuelin Dang', 'ydang@students.stab.org', 'betterRedThanExpert'])
conn.query("INSERT INTO seniorLeaves (username, name, email, password) VALUES (?, ?, ?, ?)", ['luwood', 'Lulu Wood', 'luwood@students.stab.org', 'betterRedThanExpert'])
conn.query("INSERT INTO seniorLeaves (username, name, email, password) VALUES (?, ?, ?, ?)", ['awang', 'Allen Wang', 'awang@students.stab.org', 'betterRedThanExpert'])
conn.query("INSERT INTO seniorLeaves (username, name, email, password) VALUES (?, ?, ?, ?)", ['kawang', 'Kai Wang', 'kawang@students.stab.org', 'betterRedThanExpert'])
conn.query("INSERT INTO seniorLeaves (username, name, email, password) VALUES (?, ?, ?, ?)", ['rowang', 'Roy Wang', 'roywang@students.stab.org', 'betterRedThanExpert'])
conn.query("INSERT INTO seniorLeaves (username, name, email, password) VALUES (?, ?, ?, ?)", ['fquan', 'Freddie Quan', 'fquan@students.stab.org', 'betterRedThanExpert'])
conn.query("INSERT INTO seniorLeaves (username, name, email, password) VALUES (?, ?, ?, ?)", ['csmith', 'Christian Smith', 'csmith@students.stab.org', 'betterRedThanExpert'])
conn.query("INSERT INTO seniorLeaves (username, name, email, password) VALUES (?, ?, ?, ?)", ['vichen', 'Vivian Chen', 'vichen@students.stab.org', 'betterRedThanExpert'])
conn.query("INSERT INTO seniorLeaves (username, name, email, password) VALUES (?, ?, ?, ?)", ['jzhou', 'Johnson Zhou', 'jzhou@students.stab.org', 'betterRedThanExpert'])
conn.query("INSERT INTO seniorLeaves (username, name, email, password) VALUES (?, ?, ?, ?)", ['jajohnson', 'Javon Johnson', 'jjohnson@students.stab.org', 'betterRedThanExpert'])
conn.query("INSERT INTO seniorLeaves (username, name, email, password) VALUES (?, ?, ?, ?)", ['inalic', 'Irfan Nalic', 'inalic@students.stab.org', 'betterRedThanExpert'])
conn.query("INSERT INTO seniorLeaves (username, name, email, password) VALUES (?, ?, ?, ?)", ['ecai', 'Emily Cai', 'ecai@students.stab.org', 'betterRedThanExpert'])
conn.query("INSERT INTO seniorLeaves (username, name, email, password) VALUES (?, ?, ?, ?)", ['jamullins', 'Jackson Mullins', 'jmullins@students.stab.org', 'betterRedThanExpert'])
conn.query("INSERT INTO seniorLeaves (username, name, email, password) VALUES (?, ?, ?, ?)", ['bdang', 'Bob Dang', 'bdang@students.stab.org', 'betterRedThanExpert'])
conn.query("INSERT INTO seniorLeaves (username, name, email, password) VALUES (?, ?, ?, ?)", ['aforward', 'Annabel Forward', 'aforward@students.stab.org', 'betterRedThanExpert'])
conn.query("INSERT INTO seniorLeaves (username, name, email, password) VALUES (?, ?, ?, ?)", ['cjones3', 'Catie Jones', 'catjones@students.stab.org', 'betterRedThanExpert'])
conn.query("INSERT INTO seniorLeaves (username, name, email, password) VALUES (?, ?, ?, ?)", ['skim', 'Sam Kim', 'skim@students.stab.org', 'aa'])
conn.query("INSERT INTO seniorLeaves (username, name, email, password) VALUES (?, ?, ?, ?)", ['brickards', 'Bruce Rickards', 'brickards@students.stab.org', 'betterRedThanExpert'])
conn.query("INSERT INTO seniorLeaves (username, name, email, password) VALUES (?, ?, ?, ?)", ['jperkins2', 'Jeffery Perkins', 'jperkins@students.stab.org', 'betterRedThanExpert'])
conn.query("INSERT INTO seniorLeaves (username, name, email, password) VALUES (?, ?, ?, ?)", ['smoore', 'Savraj Moore', 'samoore@students.stab.org', 'betterRedThanExpert'])
conn.query("INSERT INTO seniorLeaves (username, name, email, password) VALUES (?, ?, ?, ?)", ['luscott', 'Luke Scott', 'lscott@students.stab.org', 'betterRedThanExpert'])
conn.query("INSERT INTO seniorLeaves (username, name, email, password) VALUES (?, ?, ?, ?)", ['lmalufmas', 'Lara Maluf Mas', 'lmalufmas@students.stab.org', 'betterRedThanExpert'])
conn.query("INSERT INTO seniorLeaves (username, name, email, password) VALUES (?, ?, ?, ?)", ['vinguyen', 'Nathan Nguyen', 'vnguyen@students.stab.org', 'betterRedThanExpert'])
conn.query("INSERT INTO seniorLeaves (username, name, email, password) VALUES (?, ?, ?, ?)", ['mbabbott', 'Michael Babbott', 'mbabbott@students.stab.org', 'betterRedThanExpert'])
conn.query("INSERT INTO seniorLeaves (username, name, email, password) VALUES (?, ?, ?, ?)", ['mtran', 'Toby Tran', 'mtran@students.stab.org', 'betterRedThanExpert'])
conn.query("INSERT INTO seniorLeaves (username, name, email, password) VALUES (?, ?, ?, ?)", ['clongo', 'Claire Longo', 'clongo@students.stab.org', 'betterRedThanExpert'])
conn.query("INSERT INTO seniorLeaves (username, name, email, password) VALUES (?, ?, ?, ?)", ['jfife', 'Jack Fife', 'jfife@students.stab.org', 'betterRedThanExpert'])
conn.query("INSERT INTO seniorLeaves (username, name, email, password) VALUES (?, ?, ?, ?)", ['cmckenney', 'Claire McKenny', 'cmckenney@students.stab.org', 'betterRedThanExpert'])
conn.query("INSERT INTO seniorLeaves (username, name, email, password) VALUES (?, ?, ?, ?)", ['jufreeman', 'Julia Freeman', 'jfreeman@students.stab.org', 'betterRedThanExpert'])
conn.query("INSERT INTO seniorLeaves (username, name, email, password) VALUES (?, ?, ?, ?)", ['mkrupnick', 'Max Krupnick', 'mkrupnick@students.stab.org', 'betterRedThanExpert'])
conn.query("INSERT INTO seniorLeaves (username, name, email, password) VALUES (?, ?, ?, ?)", ['evick', 'Ellie Vick', 'evick@students.stab.org', 'betterRedThanExpert'])
conn.query("INSERT INTO seniorLeaves (username, name, email, password) VALUES (?, ?, ?, ?)", ['jpennix', 'Jordan Pennix', 'jpennix@students.stab.org', 'betterRedThanExpert'])



